[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "http://helinyu.site"
  to = "http://8.138.178.4/"
  status = 301
  force = true